# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6e945eed3b0bd333d825441003d0cc5aaea511ba977915a28d5cca0d737f93ac7bfa028892be0e5320e3929a9444661bbfdb1be05cdf2819909c05d38836958

test:
  secret_key_base: 0713d788310ecda869deed929cfe299a25d1693cca75f86b4aab6fe8adf49d784f75a3e639cfdfaf18e70e50b219ee1306ac1acf46a4b0387a85b0ac32b75409

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
